[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "daily_ai"
version = "0.0.1"
description = "Orchestrator for AI bots with Daily"
dependencies = [
    "aiohttp",
    "azure-cognitiveservices-speech",
    "daily-python",
    "fal",
    "faster_whisper",
    "groq",
    "google-cloud-texttospeech",
    "numpy",
    "openai",
    "Pillow",
    "pyht",
    "pysbd",
    "python-dotenv",
    "torch",
    "torchaudio",
    "pyaudio",
    "typing-extensions"
]

[tool.setuptools.packages.find]
# All the following settings are optional:
where = ["src"]
